# output configuration options
# output:
  # Format: colored-line-number|line-number|json|tab|checkstyle|code-climate|junit-xml|github-actions
  #
  # Multiple can be specified by separating them by comma, output can be provided
  # for each of them by separating format name and path by colon symbol.
  # Output path can be either `stdout`, `stderr` or path to the file to write to.
  # Example: "checkstyle:report.json,colored-line-number"
  #
  # Default: colored-line-number
  # format: json

linters:
  disable:
  - scopelint
  - ifshort
  - structcheck
  - exhaustivestruct
  - nosnakecase
  - interfacer
  - maligned
  - golint
  - deadcode
  - varcheck
  - rowserrcheck
  - sqlclosecheck
  - structcheck
  - wastedassign
  - gci

  # Enable presets.
  # https://golangci-lint.run/usage/linters
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused
